apiVersion: v1
kind: Service
metadata:
  name: flask
  labels: # Les même labels que dans le deployement associé
    app: flask
    role: front
spec:
  selector:
    app: flask
    role: front
  ports:
  - port: 8080
    targetPort: 8080
