apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels: # Les même labels que dans le deployement associé
    app: nginx
    role: requesthandler
spec:
  selector:
    app: nginx
    role: requesthandler
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000 # On fixe le port du noeud pour faciliter l'accès au service dans le navigateur
