apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    role: requesthandler
spec:
  selector:
    matchLabels:
      app: nginx
      role: requesthandler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        role: requesthandler
    spec:
      containers:
      - name: nginx
        image: ccmm99/info910_nginx # On précise l'image à récupérer
        resources: # On précise les ressources que l'on alloue
          limits:
            memory: "100Mi"
            cpu: "350m"
          requests:
            memory: "20Mi"
            cpu: "75m"
        ports:
        - containerPort: 80 # Le deployement doit être accessible sur le port 80
